### PR TITLE
Document which versions of Puppet this should work with

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Closes #47

**Comment by ghoneycutt** [comment]
No.. and just because it is meant to work with Puppet 5.5.8 and greater doesn't mean that's true either :)

**Comment by ghoneycutt** [comment]
Could someone review?

**Comment by ghoneycutt** [comment]
@alexjfisher could you please merge or close

**Comment by alexjfisher** [comment]
Sure.  I was going to merge, (after all, nobody has suggested any better wording!), but merged https://github.com/voxpupuli/hiera-eyaml-gpg/pull/53 first, and now this PR needs a rebase.

Maybe it's not needed any more since https://github.com/voxpupuli/hiera-eyaml-gpg/pull/55/files#diff-8e16d53d3e8f348293d936c37d2f4f97R20 ??  Up to you.  If you rebase it, I'll merge it.

**Pull request merged**
